# Generated by Django 2.2.15 on 2020-08-24 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(verbose_name='Start Date')),
                ('toDate', models.DateField(verbose_name='End Date')),
                ('shippingDate', models.DateField(blank=True, null=True, verbose_name='Shipping Date')),
                ('returnDate', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('purpose', models.CharField(blank=True, max_length=100, verbose_name='Purpose')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
                ('ownerGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Group', verbose_name='Owner Group')),
                ('ownerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner User')),
            ],
            options={
                'ordering': ['asset', 'fromDate'],
            },
        ),
    ]
